apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
spec:
  type: ClusterIP
  selector:
    app: multi-container-app 
  ports:
  - name: nginx-port
    port: 9001
    targetPort: 80
  - name: multitool-port
    port: 9002
    targetPort: 8080
